name: Main

on:
  push:
    branches:
      - main
      - release/**
    tags:
      - "v*.*.*"
    paths:
      - ".github/workflows/ci_main.yaml"
      - "*.go"
      - "go.mod"
      - "go.sum"
      - "cmd/**"
      - "config/**"
      - "test/**"
  pull_request:
    branches:
      - main

env:
  GOLANG_CI_LINT_VERSION: v1.52.2

jobs:
  check:
    name: Check
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ["1.16", "1.17", "1.18", "1.19", "1.20"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GOLANG_CI_LINT_VERSION }}
          args: --timeout=10m

      - name: Test
        run: go test -v ./...

      - name: Build
        run: go build -o /tmp/jsonfmt .
